# This file was automatically generated by SWIG (http://www.swig.org).
# Version 4.0.2
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info < (2, 7, 0):
    raise RuntimeError("Python 2.7 or later required")

# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _complex_fem
else:
    import _complex_fem

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

_swig_new_instance_method = _complex_fem.SWIG_PyInstanceMethod_New
_swig_new_static_method = _complex_fem.SWIG_PyStaticMethod_New

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "thisown":
            self.this.own(value)
        elif name == "this":
            set(self, name, value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


import weakref

import mfem._ser.vector
import mfem._ser.array
import mfem._ser.mem_manager
import mfem._ser.fespace
import mfem._ser.coefficient
import mfem._ser.globals
import mfem._ser.matrix
import mfem._ser.operators
import mfem._ser.symmat
import mfem._ser.intrules
import mfem._ser.sparsemat
import mfem._ser.densemat
import mfem._ser.eltrans
import mfem._ser.fe
import mfem._ser.geom
import mfem._ser.fe_base
import mfem._ser.fe_fixed_order
import mfem._ser.element
import mfem._ser.table
import mfem._ser.hash
import mfem._ser.fe_h1
import mfem._ser.fe_nd
import mfem._ser.fe_rt
import mfem._ser.fe_l2
import mfem._ser.fe_nurbs
import mfem._ser.fe_pos
import mfem._ser.fe_ser
import mfem._ser.mesh
import mfem._ser.sort_pairs
import mfem._ser.ncmesh
import mfem._ser.gridfunc
import mfem._ser.bilininteg
import mfem._ser.fe_coll
import mfem._ser.lininteg
import mfem._ser.linearform
import mfem._ser.nonlininteg
import mfem._ser.vertex
import mfem._ser.vtk
import mfem._ser.std_vectors
import mfem._ser.doftrans
import mfem._ser.handle
import mfem._ser.restriction
import mfem._ser.complex_operator
import mfem._ser.bilinearform
class ComplexGridFunction(mfem._ser.vector.Vector):
    r"""Proxy of C++ mfem::ComplexGridFunction class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, f):
        r"""__init__(ComplexGridFunction self, FiniteElementSpace f) -> ComplexGridFunction"""
        _complex_fem.ComplexGridFunction_swiginit(self, _complex_fem.new_ComplexGridFunction(f))

    def Update(self):
        r"""Update(ComplexGridFunction self)"""
        return _complex_fem.ComplexGridFunction_Update(self)
    Update = _swig_new_instance_method(_complex_fem.ComplexGridFunction_Update)

    def ProjectCoefficient(self, *args):
        r"""
        ProjectCoefficient(ComplexGridFunction self, Coefficient real_coeff, Coefficient imag_coeff)
        ProjectCoefficient(ComplexGridFunction self, VectorCoefficient real_vcoeff, VectorCoefficient imag_vcoeff)
        """
        return _complex_fem.ComplexGridFunction_ProjectCoefficient(self, *args)
    ProjectCoefficient = _swig_new_instance_method(_complex_fem.ComplexGridFunction_ProjectCoefficient)

    def ProjectBdrCoefficient(self, real_coeff, imag_coeff, attr):
        r"""ProjectBdrCoefficient(ComplexGridFunction self, Coefficient real_coeff, Coefficient imag_coeff, intArray attr)"""
        return _complex_fem.ComplexGridFunction_ProjectBdrCoefficient(self, real_coeff, imag_coeff, attr)
    ProjectBdrCoefficient = _swig_new_instance_method(_complex_fem.ComplexGridFunction_ProjectBdrCoefficient)

    def ProjectBdrCoefficientNormal(self, real_coeff, imag_coeff, attr):
        r"""ProjectBdrCoefficientNormal(ComplexGridFunction self, VectorCoefficient real_coeff, VectorCoefficient imag_coeff, intArray attr)"""
        return _complex_fem.ComplexGridFunction_ProjectBdrCoefficientNormal(self, real_coeff, imag_coeff, attr)
    ProjectBdrCoefficientNormal = _swig_new_instance_method(_complex_fem.ComplexGridFunction_ProjectBdrCoefficientNormal)

    def ProjectBdrCoefficientTangent(self, real_coeff, imag_coeff, attr):
        r"""ProjectBdrCoefficientTangent(ComplexGridFunction self, VectorCoefficient real_coeff, VectorCoefficient imag_coeff, intArray attr)"""
        return _complex_fem.ComplexGridFunction_ProjectBdrCoefficientTangent(self, real_coeff, imag_coeff, attr)
    ProjectBdrCoefficientTangent = _swig_new_instance_method(_complex_fem.ComplexGridFunction_ProjectBdrCoefficientTangent)

    def FESpace(self, *args):
        r"""
        FESpace(ComplexGridFunction self) -> FiniteElementSpace
        FESpace(ComplexGridFunction self) -> FiniteElementSpace
        """
        return _complex_fem.ComplexGridFunction_FESpace(self, *args)
    FESpace = _swig_new_instance_method(_complex_fem.ComplexGridFunction_FESpace)

    def real(self, *args):
        r"""
        real(ComplexGridFunction self) -> GridFunction
        real(ComplexGridFunction self) -> GridFunction
        """
        return _complex_fem.ComplexGridFunction_real(self, *args)
    real = _swig_new_instance_method(_complex_fem.ComplexGridFunction_real)

    def imag(self, *args):
        r"""
        imag(ComplexGridFunction self) -> GridFunction
        imag(ComplexGridFunction self) -> GridFunction
        """
        return _complex_fem.ComplexGridFunction_imag(self, *args)
    imag = _swig_new_instance_method(_complex_fem.ComplexGridFunction_imag)

    def Sync(self):
        r"""Sync(ComplexGridFunction self)"""
        return _complex_fem.ComplexGridFunction_Sync(self)
    Sync = _swig_new_instance_method(_complex_fem.ComplexGridFunction_Sync)

    def SyncAlias(self):
        r"""SyncAlias(ComplexGridFunction self)"""
        return _complex_fem.ComplexGridFunction_SyncAlias(self)
    SyncAlias = _swig_new_instance_method(_complex_fem.ComplexGridFunction_SyncAlias)
    __swig_destroy__ = _complex_fem.delete_ComplexGridFunction

# Register ComplexGridFunction in _complex_fem:
_complex_fem.ComplexGridFunction_swigregister(ComplexGridFunction)

class ComplexLinearForm(mfem._ser.vector.Vector):
    r"""Proxy of C++ mfem::ComplexLinearForm class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        r"""
        __init__(ComplexLinearForm self, FiniteElementSpace fes, mfem::ComplexOperator::Convention convention=HERMITIAN) -> ComplexLinearForm
        __init__(ComplexLinearForm self, FiniteElementSpace fes, LinearForm lf_r, LinearForm lf_i, mfem::ComplexOperator::Convention convention=HERMITIAN) -> ComplexLinearForm
        """
        _complex_fem.ComplexLinearForm_swiginit(self, _complex_fem.new_ComplexLinearForm(*args))
    __swig_destroy__ = _complex_fem.delete_ComplexLinearForm

    def GetConvention(self):
        r"""GetConvention(ComplexLinearForm self) -> mfem::ComplexOperator::Convention"""
        return _complex_fem.ComplexLinearForm_GetConvention(self)
    GetConvention = _swig_new_instance_method(_complex_fem.ComplexLinearForm_GetConvention)

    def SetConvention(self, convention):
        r"""SetConvention(ComplexLinearForm self, mfem::ComplexOperator::Convention const & convention)"""
        return _complex_fem.ComplexLinearForm_SetConvention(self, convention)
    SetConvention = _swig_new_instance_method(_complex_fem.ComplexLinearForm_SetConvention)

    def AddDomainIntegrator(self, *args):
        r"""
        AddDomainIntegrator(ComplexLinearForm self, LinearFormIntegrator lfi_real, LinearFormIntegrator lfi_imag)
        AddDomainIntegrator(ComplexLinearForm self, LinearFormIntegrator lfi_real, LinearFormIntegrator lfi_imag, intArray elem_attr_marker)
        """
        val = _complex_fem.ComplexLinearForm_AddDomainIntegrator(self, *args)

        self._intg = args
        if  hasattr(args[0], "thisown"): args[0].thisown=0
        if  hasattr(args[1], "thisown"): args[1].thisown=0


        return val


    def AddBoundaryIntegrator(self, *args):
        r"""
        AddBoundaryIntegrator(ComplexLinearForm self, LinearFormIntegrator lfi_real, LinearFormIntegrator lfi_imag)
        AddBoundaryIntegrator(ComplexLinearForm self, LinearFormIntegrator lfi_real, LinearFormIntegrator lfi_imag, intArray bdr_attr_marker)
        """
        val = _complex_fem.ComplexLinearForm_AddBoundaryIntegrator(self, *args)

        self._intg = args
        if  hasattr(args[0], "thisown"): args[0].thisown=0
        if  hasattr(args[1], "thisown"): args[1].thisown=0


        return val


    def AddBdrFaceIntegrator(self, *args):
        r"""
        AddBdrFaceIntegrator(ComplexLinearForm self, LinearFormIntegrator lfi_real, LinearFormIntegrator lfi_imag)
        AddBdrFaceIntegrator(ComplexLinearForm self, LinearFormIntegrator lfi_real, LinearFormIntegrator lfi_imag, intArray bdr_attr_marker)
        """
        val = _complex_fem.ComplexLinearForm_AddBdrFaceIntegrator(self, *args)

        self._intg = args
        if  hasattr(args[0], "thisown"): args[0].thisown=0
        if  hasattr(args[1], "thisown"): args[1].thisown=0


        return val


    def FESpace(self):
        r"""FESpace(ComplexLinearForm self) -> FiniteElementSpace"""
        return _complex_fem.ComplexLinearForm_FESpace(self)
    FESpace = _swig_new_instance_method(_complex_fem.ComplexLinearForm_FESpace)

    def real(self, *args):
        r"""
        real(ComplexLinearForm self) -> LinearForm
        real(ComplexLinearForm self) -> LinearForm
        """
        return _complex_fem.ComplexLinearForm_real(self, *args)
    real = _swig_new_instance_method(_complex_fem.ComplexLinearForm_real)

    def imag(self, *args):
        r"""
        imag(ComplexLinearForm self) -> LinearForm
        imag(ComplexLinearForm self) -> LinearForm
        """
        return _complex_fem.ComplexLinearForm_imag(self, *args)
    imag = _swig_new_instance_method(_complex_fem.ComplexLinearForm_imag)

    def Sync(self):
        r"""Sync(ComplexLinearForm self)"""
        return _complex_fem.ComplexLinearForm_Sync(self)
    Sync = _swig_new_instance_method(_complex_fem.ComplexLinearForm_Sync)

    def SyncAlias(self):
        r"""SyncAlias(ComplexLinearForm self)"""
        return _complex_fem.ComplexLinearForm_SyncAlias(self)
    SyncAlias = _swig_new_instance_method(_complex_fem.ComplexLinearForm_SyncAlias)

    def Update(self, *args):
        r"""
        Update(ComplexLinearForm self)
        Update(ComplexLinearForm self, FiniteElementSpace f)
        """
        return _complex_fem.ComplexLinearForm_Update(self, *args)
    Update = _swig_new_instance_method(_complex_fem.ComplexLinearForm_Update)

    def Assemble(self):
        r"""Assemble(ComplexLinearForm self)"""
        return _complex_fem.ComplexLinearForm_Assemble(self)
    Assemble = _swig_new_instance_method(_complex_fem.ComplexLinearForm_Assemble)

    def __call__(self, gf):
        r"""__call__(ComplexLinearForm self, ComplexGridFunction gf) -> std::complex< double >"""
        return _complex_fem.ComplexLinearForm___call__(self, gf)
    __call__ = _swig_new_instance_method(_complex_fem.ComplexLinearForm___call__)

# Register ComplexLinearForm in _complex_fem:
_complex_fem.ComplexLinearForm_swigregister(ComplexLinearForm)

class SesquilinearForm(object):
    r"""Proxy of C++ mfem::SesquilinearForm class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        r"""
        __init__(SesquilinearForm self, FiniteElementSpace fes, mfem::ComplexOperator::Convention convention=HERMITIAN) -> SesquilinearForm
        __init__(SesquilinearForm self, FiniteElementSpace fes, BilinearForm bfr, BilinearForm bfi, mfem::ComplexOperator::Convention convention=HERMITIAN) -> SesquilinearForm
        """
        _complex_fem.SesquilinearForm_swiginit(self, _complex_fem.new_SesquilinearForm(*args))

    def GetConvention(self):
        r"""GetConvention(SesquilinearForm self) -> mfem::ComplexOperator::Convention"""
        return _complex_fem.SesquilinearForm_GetConvention(self)
    GetConvention = _swig_new_instance_method(_complex_fem.SesquilinearForm_GetConvention)

    def SetConvention(self, convention):
        r"""SetConvention(SesquilinearForm self, mfem::ComplexOperator::Convention const & convention)"""
        return _complex_fem.SesquilinearForm_SetConvention(self, convention)
    SetConvention = _swig_new_instance_method(_complex_fem.SesquilinearForm_SetConvention)

    def SetAssemblyLevel(self, assembly_level):
        r"""SetAssemblyLevel(SesquilinearForm self, mfem::AssemblyLevel assembly_level)"""
        return _complex_fem.SesquilinearForm_SetAssemblyLevel(self, assembly_level)
    SetAssemblyLevel = _swig_new_instance_method(_complex_fem.SesquilinearForm_SetAssemblyLevel)

    def real(self, *args):
        r"""
        real(SesquilinearForm self) -> BilinearForm
        real(SesquilinearForm self) -> BilinearForm
        """
        return _complex_fem.SesquilinearForm_real(self, *args)
    real = _swig_new_instance_method(_complex_fem.SesquilinearForm_real)

    def imag(self, *args):
        r"""
        imag(SesquilinearForm self) -> BilinearForm
        imag(SesquilinearForm self) -> BilinearForm
        """
        return _complex_fem.SesquilinearForm_imag(self, *args)
    imag = _swig_new_instance_method(_complex_fem.SesquilinearForm_imag)

    def AddDomainIntegrator(self, *args):
        r"""
        AddDomainIntegrator(SesquilinearForm self, BilinearFormIntegrator bfi_real, BilinearFormIntegrator bfi_imag)
        AddDomainIntegrator(SesquilinearForm self, BilinearFormIntegrator bfi_real, BilinearFormIntegrator bfi_imag, intArray elem_marker)
        """
        val = _complex_fem.SesquilinearForm_AddDomainIntegrator(self, *args)

        self._intg = args
        if  hasattr(args[0], "thisown"): args[0].thisown=0
        if  hasattr(args[1], "thisown"): args[1].thisown=0


        return val


    def AddBoundaryIntegrator(self, *args):
        r"""
        AddBoundaryIntegrator(SesquilinearForm self, BilinearFormIntegrator bfi_real, BilinearFormIntegrator bfi_imag)
        AddBoundaryIntegrator(SesquilinearForm self, BilinearFormIntegrator bfi_real, BilinearFormIntegrator bfi_imag, intArray bdr_marker)
        """
        val = _complex_fem.SesquilinearForm_AddBoundaryIntegrator(self, *args)

        self._intg = args
        if  hasattr(args[0], "thisown"): args[0].thisown=0
        if  hasattr(args[1], "thisown"): args[1].thisown=0


        return val


    def AddInteriorFaceIntegrator(self, bfi_real, bfi_imag):
        r"""AddInteriorFaceIntegrator(SesquilinearForm self, BilinearFormIntegrator bfi_real, BilinearFormIntegrator bfi_imag)"""
        val = _complex_fem.SesquilinearForm_AddInteriorFaceIntegrator(self, bfi_real, bfi_imag)

        self._intg = (bfi_real, bfi_imag)
        if hasattr(bfi_real, "thisown"): bfi_real.thisown=0
        if hasattr(bfi_imag, "thisown"): bfi_imag.thisown=0


        return val


    def AddBdrFaceIntegrator(self, *args):
        r"""
        AddBdrFaceIntegrator(SesquilinearForm self, BilinearFormIntegrator bfi_real, BilinearFormIntegrator bfi_imag)
        AddBdrFaceIntegrator(SesquilinearForm self, BilinearFormIntegrator bfi_real, BilinearFormIntegrator bfi_imag, intArray bdr_marker)
        """
        val = _complex_fem.SesquilinearForm_AddBdrFaceIntegrator(self, *args)

        self._intg = args
        if  hasattr(args[0], "thisown"): args[0].thisown=0
        if  hasattr(args[1], "thisown"): args[1].thisown=0


        return val


    def Assemble(self, skip_zeros=1):
        r"""Assemble(SesquilinearForm self, int skip_zeros=1)"""
        return _complex_fem.SesquilinearForm_Assemble(self, skip_zeros)
    Assemble = _swig_new_instance_method(_complex_fem.SesquilinearForm_Assemble)

    def Finalize(self, skip_zeros=1):
        r"""Finalize(SesquilinearForm self, int skip_zeros=1)"""
        return _complex_fem.SesquilinearForm_Finalize(self, skip_zeros)
    Finalize = _swig_new_instance_method(_complex_fem.SesquilinearForm_Finalize)

    def AssembleComplexSparseMatrix(self):
        r"""AssembleComplexSparseMatrix(SesquilinearForm self) -> ComplexSparseMatrix"""
        return _complex_fem.SesquilinearForm_AssembleComplexSparseMatrix(self)
    AssembleComplexSparseMatrix = _swig_new_instance_method(_complex_fem.SesquilinearForm_AssembleComplexSparseMatrix)

    def FESpace(self):
        r"""FESpace(SesquilinearForm self) -> FiniteElementSpace"""
        return _complex_fem.SesquilinearForm_FESpace(self)
    FESpace = _swig_new_instance_method(_complex_fem.SesquilinearForm_FESpace)

    def FormLinearSystem(self, ess_tdof_list, x, b, A, X, B, copy_interior=0):
        r"""FormLinearSystem(SesquilinearForm self, intArray ess_tdof_list, Vector x, Vector b, OperatorHandle A, Vector X, Vector B, int copy_interior=0)"""
        return _complex_fem.SesquilinearForm_FormLinearSystem(self, ess_tdof_list, x, b, A, X, B, copy_interior)
    FormLinearSystem = _swig_new_instance_method(_complex_fem.SesquilinearForm_FormLinearSystem)

    def FormSystemMatrix(self, ess_tdof_list, A):
        r"""FormSystemMatrix(SesquilinearForm self, intArray ess_tdof_list, OperatorHandle A)"""
        return _complex_fem.SesquilinearForm_FormSystemMatrix(self, ess_tdof_list, A)
    FormSystemMatrix = _swig_new_instance_method(_complex_fem.SesquilinearForm_FormSystemMatrix)

    def RecoverFEMSolution(self, X, b, x):
        r"""RecoverFEMSolution(SesquilinearForm self, Vector X, Vector b, Vector x)"""
        return _complex_fem.SesquilinearForm_RecoverFEMSolution(self, X, b, x)
    RecoverFEMSolution = _swig_new_instance_method(_complex_fem.SesquilinearForm_RecoverFEMSolution)

    def Update(self, nfes=None):
        r"""Update(SesquilinearForm self, FiniteElementSpace nfes=None)"""
        return _complex_fem.SesquilinearForm_Update(self, nfes)
    Update = _swig_new_instance_method(_complex_fem.SesquilinearForm_Update)

    def SetDiagonalPolicy(self, dpolicy):
        r"""SetDiagonalPolicy(SesquilinearForm self, mfem::Matrix::DiagonalPolicy dpolicy)"""
        return _complex_fem.SesquilinearForm_SetDiagonalPolicy(self, dpolicy)
    SetDiagonalPolicy = _swig_new_instance_method(_complex_fem.SesquilinearForm_SetDiagonalPolicy)

    def GetDiagonalPolicy(self):
        r"""GetDiagonalPolicy(SesquilinearForm self) -> mfem::Matrix::DiagonalPolicy"""
        return _complex_fem.SesquilinearForm_GetDiagonalPolicy(self)
    GetDiagonalPolicy = _swig_new_instance_method(_complex_fem.SesquilinearForm_GetDiagonalPolicy)
    __swig_destroy__ = _complex_fem.delete_SesquilinearForm

# Register SesquilinearForm in _complex_fem:
_complex_fem.SesquilinearForm_swigregister(SesquilinearForm)



