# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.8
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_handle', [dirname(__file__)])
        except ImportError:
            import _handle
            return _handle
        if fp is not None:
            try:
                _mod = imp.load_module('_handle', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _handle = swig_import_helper()
    del swig_import_helper
else:
    import _handle
del version_info
try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.


def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr_nondynamic(self, class_type, name, static=1):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    if (not static):
        return object.__getattr__(self, name)
    else:
        raise AttributeError(name)

def _swig_getattr(self, class_type, name):
    return _swig_getattr_nondynamic(self, class_type, name, 0)


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object:
        pass
    _newclass = 0


try:
    import weakref
    weakref_proxy = weakref.proxy
except Exception:
    weakref_proxy = lambda x: x



_handle.MFEM_TIMER_TYPE_swigconstant(_handle)
MFEM_TIMER_TYPE = _handle.MFEM_TIMER_TYPE
import operators
import vector
import array
import ostream_typemap
import hypre
import sparsemat
import matrix
import densemat
import fespace
import coefficient
import intrules
import eltrans
import fe
import mesh
import ncmesh
import element
import geom
import table
import vertex
import fe_coll
import lininteg
import pfespace
import pmesh
import pncmesh
import communication
import sets
class OperatorHandle(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, OperatorHandle, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, OperatorHandle, name)
    __repr__ = _swig_repr

    def __init__(self, *args):
        this = _handle.new_OperatorHandle(*args)
        try:
            self.this.append(this)
        except Exception:
            self.this = this
    __swig_destroy__ = _handle.delete_OperatorHandle
    __del__ = lambda self: None

    def Ptr(self):
        return _handle.OperatorHandle_Ptr(self)

    def Type(self):
        return _handle.OperatorHandle_Type(self)

    def OwnsOperator(self):
        return _handle.OperatorHandle_OwnsOperator(self)

    def SetOperatorOwner(self, own=True):
        return _handle.OperatorHandle_SetOperatorOwner(self, own)

    def Clear(self):
        return _handle.OperatorHandle_Clear(self)

    def SetType(self, tid):
        return _handle.OperatorHandle_SetType(self, tid)

    def MakeSquareBlockDiag(self, comm, glob_size, row_starts, diag):
        return _handle.OperatorHandle_MakeSquareBlockDiag(self, comm, glob_size, row_starts, diag)

    def MakeRectangularBlockDiag(self, comm, glob_num_rows, glob_num_cols, row_starts, col_starts, diag):
        return _handle.OperatorHandle_MakeRectangularBlockDiag(self, comm, glob_num_rows, glob_num_cols, row_starts, col_starts, diag)

    def MakePtAP(self, A, P):
        return _handle.OperatorHandle_MakePtAP(self, A, P)

    def MakeRAP(self, Rt, A, P):
        return _handle.OperatorHandle_MakeRAP(self, Rt, A, P)

    def EliminateRowsCols(self, A, ess_dof_list):
        return _handle.OperatorHandle_EliminateRowsCols(self, A, ess_dof_list)

    def EliminateBC(self, A_e, ess_dof_list, X, B):
        return _handle.OperatorHandle_EliminateBC(self, A_e, ess_dof_list, X, B)

    def As(self):
        return _handle.OperatorHandle_As(self)

    def Is(self):
        return _handle.OperatorHandle_Is(self)

    def Get(self, A):
        return _handle.OperatorHandle_Get(self, A)

    def Reset(self, A, own_A=True):
        return _handle.OperatorHandle_Reset(self, A, own_A)

    def ConvertFrom(self, *args):
        return _handle.OperatorHandle_ConvertFrom(self, *args)
OperatorHandle_swigregister = _handle.OperatorHandle_swigregister
OperatorHandle_swigregister(OperatorHandle)

# This file is compatible with both classic and new-style classes.


