# Generated by generate_ordinary_bridge.py. Do not edit.
from importlib import import_module
from pathlib import Path

from nsb_rt.runtime.ordinary import install_bridge

_MODULES = {name: import_module(name) for name in ['mfem._ser.array', 'mfem._ser.coefficient', 'mfem._ser.densemat', 'mfem._ser.doftrans', 'mfem._ser.eltrans', 'mfem._ser.fe_base', 'mfem._ser.fespace', 'mfem._ser.hyperbolic', 'mfem._ser.intrules', 'mfem._ser.lininteg', 'mfem._ser.nonlinearform', 'mfem._ser.operators', 'mfem._ser.vector']}
install_bridge(_MODULES, Path(__file__).with_name("ordinary_descriptor.json"))

from nsb_rt import register_state_backend
from nsb_rt.runtime.director import install_director_bindings

_state_backend_module = import_module('mfem._nsb_state_bindings')
register_state_backend(
    'mfem', _state_backend_module, state_abi=6)
_director_helpers = import_module('mfem._ser.nsb_director_bindings')
_DIRECTOR_BINDINGS = install_director_bindings(
    _MODULES,
    Path(__file__).with_name("director_descriptor.json"),
    Path(__file__).with_name("ordinary_descriptor.json"),
    helper_module=_director_helpers,
)

def director_binding(cxx_type):
    return _DIRECTOR_BINDINGS[cxx_type]
