name: release_binary

on:
  push:
    tags: ["v*"]

permissions:
  contents: read

jobs:
  linux-release:
    uses: ./.github/workflows/build-binary-callable.yml
    with:
      repository-url: https://upload.pypi.org/legacy/
    secrets:
      upload-token: ${{ secrets.PYPI_TOKEN }}
