name: testrelease_binary

on:
  push:
    tags: ["test_*"]

permissions:
  contents: read

jobs:
  linux-release:
    uses: ./.github/workflows/build-binary-callable.yml
    with:
      repository-url: https://test.pypi.org/legacy/
    secrets:
      upload-token: ${{ secrets.TEST_PYPI_TOKEN }}
